name: docs-internal Moda CI

# More info on CI actions setup can be found here:
# https://github.com/github/ops/blob/master/docs/playbooks/build-systems/moving-moda-apps-from-bp-to-actions.md

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'gh-readonly-queue/**'
  merge_group:
    types: [checks_requested]

jobs:
  moda-config-bundle:
    if: ${{ github.repository == 'github/docs-internal' }}
    name: ${{ matrix.ci_job.job }}
    strategy:
      fail-fast: false
      matrix:
        ci_job: [{ 'job': 'docs-internal-moda-config-bundle' }]
    uses: github/internal-actions/.github/workflows/moda.yml@main
    with:
      ci-formatted-job-name: ${{ matrix.ci_job.job }}
      vault-keys: ${{ vars.VAULT_KEYS }}
    secrets:
      dx-bot-token: ${{ secrets.INTERNAL_ACTIONS_DX_BOT_ACCOUNT_TOKEN }}
      datadog-api-key: ${{ secrets.DATADOG_API_KEY }}

  docker-image:
    if: ${{ github.repository == 'github/docs-internal' }}
    name: ${{ matrix.ci_job.job }}
    strategy:
      fail-fast: false
      matrix:
        ci_job: [{ 'job': 'docs-internal-docker-image' }]
    uses: github/internal-actions/.github/workflows/kube.yml@main
    with:
      ci-formatted-job-name: ${{ matrix.ci_job.job }}
      vault-keys: ${{ vars.VAULT_KEYS }}
    secrets:
      dx-bot-token: ${{ secrets.INTERNAL_ACTIONS_DX_BOT_ACCOUNT_TOKEN }}
      datadog-api-key: ${{ secrets.DATADOG_API_KEY }}

  docker-security:
    if: ${{ github.repository == 'github/docs-internal' }}
    name: ${{ matrix.ci_job.job }}
    strategy:
      fail-fast: false
      matrix:
        ci_job: [{ 'job': 'docs-internal-docker-security' }]
    uses: github/internal-actions/.github/workflows/docker_security.yml@main
    with:
      ci-formatted-job-name: ${{ matrix.ci_job.job }}
      vault-keys: ${{ vars.VAULT_KEYS }}
    secrets:
      dx-bot-token: ${{ secrets.INTERNAL_ACTIONS_DX_BOT_ACCOUNT_TOKEN }}
      datadog-api-key: ${{ secrets.DATADOG_API_KEY }}

permissions:
  actions: read
  checks: read
  contents: read
  statuses: read
  id-token: write
